language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository
    - addon-google_apis-google-19

    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-17